export enum ColorEnum {
  BEIGE = 'beige',
  CLARET = 'claret',
  RED = 'red',
  GRAY = 'gray',
  YELLOW = 'yellow',
  WHITE = 'white',
  BROWN = 'brown',
  PURPLE = 'purple',
  BLUE = 'blue',
  SILVER = 'silver',
  GOLDEN = 'golden',
  BLACK = 'black',
  NAVY = 'navy',
  ORANGE = 'orange',
  GREEN = 'green',
  OTHER = 'other',
}
