export enum PasswordErrorCode {
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG = 'PASSWORD_TOO_LONG',
  PASSWORD_NO_UPPERCASE = 'PASSWORD_NO_UPPERCASE',
  PASSWORD_NO_LOWERCASE = 'PASSWORD_NO_LOWERCASE',
  PASSWORD_NO_DIGIT = 'PASSWORD_NO_DIGIT',
  PASSWORD_NO_SPECIAL = 'PASSWORD_NO_SPECIAL',
  PASSWORD_HAS_WHITESPACE = 'PASSWORD_HAS_WHITESPACE',
  PASSWORD_CONTAINS_EMAIL_PART = 'PASSWORD_CONTAINS_EMAIL_PART',
}
