export const ErrorCodes = {
  BAD_REQUEST: 'BAD_REQUEST',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DUPLICATE_KEY: 'DUPLICATE_KEY',

  BAD_ID_FORMAT: 'BAD_ID_FORMAT',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const StatusCodeMap: Record<number, ErrorCode> = {
  400: ErrorCodes.BAD_REQUEST,
  401: ErrorCodes.AUTH_UNAUTHORIZED,
  403: ErrorCodes.AUTH_FORBIDDEN,
  404: ErrorCodes.RESOURCE_NOT_FOUND,
  409: ErrorCodes.CONFLICT,
  422: ErrorCodes.VALIDATION_FAILED,
  429: ErrorCodes.RATE_LIMITED,
  500: ErrorCodes.INTERNAL_SERVER_ERROR,
};
