#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Быстрые правки только изменённых файлов
npx lint-staged

# Типы и базовые проверки всего репо
yarn typecheck
yarn lint

# Опционально — быстрый формат (если хочешь жёстко держать стиль)
# yarn format
