export enum ValidationEnum {
  MIN_PASSWORD_LENGTH = 6,
  MAX_PASSWORD_LENGTH = 16,
  MIN_FIRST_NAME_LENGTH = 2,
  MAX_FIRST_NAME_LENGTH = 25,
  MIN_LAST_NAME_LENGTH = 2,
  MAX_LAST_NAME_LENGTH = 25,
}
