export enum CareSessionKind {
  WASH_EXTERNAL = 'WASH_EXTERNAL',
  WASH_SELF_SERVICE = 'WASH_SELF_SERVICE',
  WASH_AUTO = 'WASH_AUTO',
  INTERIOR_CLEANING = 'INTERIOR_CLEANING',
  QUICK_CLEAN = 'QUICK_CLEAN',
  POLISH_PAINT = 'POLISH_PAINT',
  POLISH_HEADLIGHTS = 'POLISH_HEADLIGHTS',
  PLASTIC_RESTORATION = 'PLASTIC_RESTORATION',
  WAX = 'WAX',
  DETAILING = 'DETAILING',
  OTHER = 'OTHER',
}
